### ISSUE TITLE
使用raw-loader引发的问题

### ISSUE THREAD

**Issue by refanbanzhang** [nqdy666/wjsp#3]
在html或者jsp中使用元素行内样式设置图片需要使`<div class="banner" style="background-image: url(${require('../../assets/images/common/banner_3.png')})"></div>`这种语法，这是`HtmlWebpackPlugin`默认的ejs语法能够解析的，但是用了raw-loader之后，也就无法处理了

如果不用raw-loader，那么jsp或者ftl(freemarker)也是无法打包成功的，这两个完全冲突了

当然，如果不使用`<div class="banner" style="background-image:url(${require('../../assets/images/common/banner_3.png')})"></div>`这种语法，是可以不管这个问题的，但是，这种需求还是很强烈的，不知道有什么解决方式？

**Comment by nqdy666** [comment]
有能力的话，可以自定义loader。这样子可以赋予jsp或者ftl更多的特性。

**Comment by nqdy666** [comment]
> 在html或者jsp中使用元素行内样式设置图片需要使`<div class="banner" style="background-image: url(${require('../../assets/images/common/banner_3.png')})"></div>`这种语法，这是`HtmlWebpackPlugin`默认的ejs语法能够解析的，但是用了raw-loader之后，也就无法处理了
> 
> 如果不用raw-loader，那么jsp或者ftl(freemarker)也是无法打包成功的，这两个完全冲突了
> 
> 当然，如果不使用`<div class="banner" style="background-image:url(${require('../../assets/images/common/banner_3.png')})"></div>`这种语法，是可以不管这个问题的，但是，这种需求还是很强烈的，不知道有什么解决方式？

1、有能力的话，可以自定义loader。以便HtmlWebpackPlugin可以进行支持变量注入。
2、关于你的那一种写法，建议用前端模板处理，比如vue的，应该达到你的要求。
